version: '3'
services:
  train:
    image: petteriteikari/minivess-mlops-train:latest
    container_name: petteriteikari/minivess-mlops-train
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - dvc-cache:/mnt/minivess-dvc-cache
      - artifacts:/mnt/minivess-artifacts
    ports:
      - "8088:8088"
volumes:
  artifacts:
  dvc-cache:
