stages:
  preprocess:
    cmd: uv run python -m minivess.data.preprocess
    deps:
      - src/minivess/data/preprocess.py
      - data/raw/
    outs:
      - data/processed/
    params:
      - configs/deployment/settings.toml:
          - default.data_dir

  validate_data:
    cmd: uv run python -m minivess.validation.run
    deps:
      - src/minivess/validation/
      - data/processed/
    metrics:
      - data/validation_report.json:
          cache: false
