#!/usr/bin/env bash
# ============================================================================
# MambaVesselNet T09/T10 Overnight Smoke Test — Master Executor
# Generated by /overnight-runner skill from:
#   docs/planning/overnight-mambavesselnet.yaml
#
# Usage:
#   screen -S overnight
#   ./docs/planning/mambavesselnet-overnight-runner.sh
#   # Detach: Ctrl-A D
#   # Reattach: screen -r overnight
#
# Resume after failure:
#   SKIP_TO=1 ./docs/planning/mambavesselnet-overnight-runner.sh
# ============================================================================
set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
REPO_ROOT="/home/petteri/Dropbox/github-personal/minivess-mlops"
LOG_DIR="/tmp/minivess-overnight-mamba"
TIMEOUT_SEC=7200
BASE_BRANCH="test/mambavesselnet"
SKIP_TO="${SKIP_TO:-0}"
MASTER_LOG="${LOG_DIR}/master.log"

# Child 1
CHILD_1_PLAN="docs/planning/mambavesselnet-test-on-dev-runpod-followup.xml"
CHILD_1_LABEL="MambaVesselNet++ T09 VRAM + T10 Smoke Test on RunPod RTX 4090"
CHILD_1_BRANCH="test/mambavesselnet"
CHILD_1_LOG="${LOG_DIR}/child-1.log"

# ── Helpers ─────────────────────────────────────────────────────────────────
ts() { date '+%Y-%m-%d %H:%M:%S'; }

log_master() {
    echo "[$(ts)] [MASTER] $*" | tee -a "${MASTER_LOG}"
}

start_heartbeat() {
    while true; do
        echo "[$(ts)] [HEARTBEAT] alive — child running" >> "${MASTER_LOG}"
        sleep 60
    done &
    HEARTBEAT_PID=$!
}

start_watchdog() {
    local log_file="$1"
    local child_num="$2"
    sleep 600  # wait 10 minutes before first check
    while true; do
        if [ -f "${log_file}" ]; then
            local size
            size=$(stat --format=%s "${log_file}" 2>/dev/null || echo "0")
            if [ "${size}" -eq 0 ]; then
                log_master "STALL WARNING: child-${child_num}.log is 0 bytes after 10+ min"
            fi
        fi
        sleep 300  # re-check every 5 minutes
    done &
    WATCHDOG_PID=$!
}

kill_background() {
    if [ -n "${HEARTBEAT_PID:-}" ]; then
        kill "${HEARTBEAT_PID}" 2>/dev/null || true
        wait "${HEARTBEAT_PID}" 2>/dev/null || true
        unset HEARTBEAT_PID
    fi
    if [ -n "${WATCHDOG_PID:-}" ]; then
        kill "${WATCHDOG_PID}" 2>/dev/null || true
        wait "${WATCHDOG_PID}" 2>/dev/null || true
        unset WATCHDOG_PID
    fi
}

trap kill_background EXIT

# ── Prerequisites ───────────────────────────────────────────────────────────
prerequisites() {
    log_master "Checking prerequisites..."

    local ok=true

    if ! command -v claude &>/dev/null; then
        log_master "FATAL: claude CLI not found"
        ok=false
    fi
    if ! command -v gh &>/dev/null; then
        log_master "FATAL: gh CLI not found"
        ok=false
    fi
    if ! command -v uv &>/dev/null; then
        log_master "FATAL: uv not found"
        ok=false
    fi
    if ! command -v git &>/dev/null; then
        log_master "FATAL: git not found"
        ok=false
    fi

    # Verify git is clean (allow untracked files)
    cd "${REPO_ROOT}"
    if [ -n "$(git diff --name-only 2>/dev/null)" ]; then
        log_master "WARNING: git has uncommitted changes — proceeding anyway"
    fi

    if [ "${ok}" = false ]; then
        log_master "Prerequisites FAILED. Aborting."
        exit 1
    fi

    log_master "Prerequisites OK (claude, gh, uv, git)"
}

# ── Run Child ───────────────────────────────────────────────────────────────
run_child() {
    local num="$1"
    local plan="$2"
    local label="$3"
    local branch="$4"
    local log_file="$5"

    # Skip if requested
    if [ "${num}" -lt "${SKIP_TO}" ]; then
        log_master "SKIP child ${num}: ${label} (SKIP_TO=${SKIP_TO})"
        return 0
    fi

    log_master "════════════════════════════════════════════════════════════"
    log_master "START child ${num}: ${label}"
    log_master "  Plan:   ${plan}"
    log_master "  Branch: ${branch}"
    log_master "  Log:    ${log_file}"
    log_master "════════════════════════════════════════════════════════════"

    # Verify plan file exists
    if [ ! -f "${REPO_ROOT}/${plan}" ]; then
        log_master "FATAL: plan file not found: ${plan}"
        return 1
    fi

    # Checkout branch
    cd "${REPO_ROOT}"
    git checkout "${branch}" 2>/dev/null || git checkout -b "${branch}"

    # Truncate log (watchdog baseline)
    : > "${log_file}"

    # Start background monitors
    start_heartbeat
    start_watchdog "${log_file}" "${num}"

    # Build prompt — short, delegates to plan file
    local prompt
    prompt="$(cat <<PROMPT_EOF
You are executing an overnight autonomous smoke test plan for the MinIVess MLOps repo.

REPO ROOT: ${REPO_ROOT}
PLAN FILE: ${REPO_ROOT}/${plan}

Read the plan file above FIRST, then execute every phase in order (P1 through P5).

CRITICAL RULES (from CLAUDE.md — non-negotiable):
- TDD: write failing tests first (RED), then minimum implementation (GREEN)
- Library-First: use MONAI, Prefect, existing code before writing custom logic
- No regex for structured data (use ast, yaml, json parsers)
- Docker = execution model. SkyPilot = intercloud broker.
- /tmp FORBIDDEN for persistent artifacts (OK for build logs)
- .env.example = single source of truth
- GitHub Actions EXPLICITLY DISABLED (never add triggers)
- Every test failure must be fixed or reported immediately
- NEVER ask the user questions — query CLI tools instead (sky status, docker manifest inspect, etc.)
- On unrecoverable failure: create GitHub issue with diagnosis and EXIT CLEANLY

BUDGET: \$2.00 max cloud spend. RunPod balance: \$8.18.

After all phases complete successfully:
1. Run make test-staging to verify nothing broke
2. Commit VRAM measurement to configs/model_profiles/mambavesselnet.yaml
3. Close #744 with the VRAM measurement
4. Push branch and create PR test/mambavesselnet -> main via gh pr create
5. Report final status
PROMPT_EOF
)"

    # Run claude headless with timeout, streaming output
    local exit_code=0
    timeout "${TIMEOUT_SEC}" claude -p "${prompt}" \
        --dangerously-skip-permissions \
        --output-format stream-json \
        --verbose \
        2>&1 | tee "${log_file}" | \
        jq -rj 'select(.type=="assistant" and .message.content?) |
            .message.content[] |
            select(.type=="text") |
            .text' 2>/dev/null || exit_code=$?

    # Kill background processes
    kill_background

    # Report result
    if [ "${exit_code}" -eq 0 ]; then
        log_master "DONE child ${num}: ${label} — SUCCESS"
    elif [ "${exit_code}" -eq 124 ]; then
        log_master "TIMEOUT child ${num}: ${label} — killed after ${TIMEOUT_SEC}s"
    else
        log_master "FAILED child ${num}: ${label} — exit code ${exit_code}"
    fi

    return "${exit_code}"
}

# ── Main ────────────────────────────────────────────────────────────────────
main() {
    mkdir -p "${LOG_DIR}"
    : > "${MASTER_LOG}"

    log_master "══════════════════════════════════════════════════════════════"
    log_master "MambaVesselNet T09/T10 Overnight Smoke Test"
    log_master "  Config:  docs/planning/overnight-mambavesselnet.yaml"
    log_master "  Repo:    ${REPO_ROOT}"
    log_master "  Timeout: ${TIMEOUT_SEC}s per child"
    log_master "  Log dir: ${LOG_DIR}"
    log_master "══════════════════════════════════════════════════════════════"

    prerequisites

    # ── Child 1: MambaVesselNet Smoke Test ──
    local result=0
    run_child 1 \
        "${CHILD_1_PLAN}" \
        "${CHILD_1_LABEL}" \
        "${CHILD_1_BRANCH}" \
        "${CHILD_1_LOG}" || result=$?

    # ── Post-Run Summary ──
    log_master "══════════════════════════════════════════════════════════════"
    log_master "BATCH COMPLETE"
    if [ "${result}" -eq 0 ]; then
        log_master "  Child 1: SUCCESS"
    elif [ "${result}" -eq 124 ]; then
        log_master "  Child 1: TIMEOUT"
    else
        log_master "  Child 1: FAILED (exit ${result})"
    fi
    log_master "══════════════════════════════════════════════════════════════"

    # Check for PRs created
    log_master "Checking for PRs on branch ${CHILD_1_BRANCH}..."
    cd "${REPO_ROOT}"
    gh pr list --head "${CHILD_1_BRANCH}" --json number,title,url 2>/dev/null | \
        tee -a "${MASTER_LOG}" || true

    # Check issue #744 state
    log_master "Issue #744 state:"
    gh issue view 744 --json state,title 2>/dev/null | \
        tee -a "${MASTER_LOG}" || true

    log_master "Logs available at: ${LOG_DIR}/"
    log_master "Master log: ${MASTER_LOG}"
    log_master "Child log:  ${CHILD_1_LOG}"

    return "${result}"
}

main "$@"
