NAME: 'test_dataload'
# TODO! update the changed keys in the config
config:
  VERBOSE: True
  TRAINING:
    SKIP_TRAINING: True
  DATA:
    DATA_SOURCE:
      MINIVESS:
        DATASET:
          # Use the non-caching vanilla Dataset
          NAME: 'MONAI_DATASET'