# @package _global_
NAME: 'train_placeholder_cfg'
config:
  VERBOSE: True
  TRAINING:
    # When you add some tests that check if your weights are changing, something is learned (e.g. Weightwatcher),
    # you could want to train a bit longer. 1 epoch is enough for the basic bug hunting
    NUM_EPOCHS: 1
  DATA:
    DATA_SOURCE:
      MINIVESS:
        DATASET:
          MONAI_CACHEDATASET:
            CACHE_RATE: 1.0
        SUBSET:
          NAME: 'DEBUG'
  LOGGING:
    MLFLOW:
      TRACKING:
        enable: True
  TESTING:
    # We have ran the dataloader test before this, anbd the train test will not be run if
    # the dataloader test failed, so need to test this again
    DATALOADER:
      DATA_VALIDITY:
        enable: False