# @package _global_
NAME: 'test_dataload'
config:
  VERBOSE: True
  TRAINING:
    SKIP_TRAINING: True
  DATA:
    DATA_SOURCE:
      MINIVESS:
        DATASET:
          MONAI_CACHEDATASET:
            CACHE_RATE: 0.0