#!/usr/bin/env python
"""Index all planning docs by parsing YAML frontmatter and generating STATUS.yaml.

Usage::

    uv run python scripts/index_planning_docs.py
    uv run python scripts/index_planning_docs.py --planning-dir docs/planning
"""

from __future__ import annotations

import argparse
import sys
import warnings
from datetime import UTC, datetime
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Status ordering: active first, then implemented, planned, reference
STATUS_ORDER: dict[str, int] = {
    "active": 0,
    "implemented": 1,
    "planned": 2,
    "reference": 3,
}


def _parse_frontmatter(path: Path) -> dict[str, str] | None:
    """Extract YAML frontmatter from a Markdown file.

    Frontmatter is delimited by ``---`` on its own line at the very start
    of the file.  Returns the parsed dict, or ``None`` when no valid
    frontmatter is found.
    """
    text = path.read_text(encoding="utf-8")
    lines = text.split("\n")

    # First line must be the opening delimiter
    if not lines or lines[0].strip() != "---":
        return None

    # Find closing delimiter
    closing_idx: int | None = None
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            closing_idx = idx
            break

    if closing_idx is None:
        return None

    frontmatter_text = "\n".join(lines[1:closing_idx])
    try:
        data = yaml.safe_load(frontmatter_text)
    except yaml.YAMLError:
        return None

    if not isinstance(data, dict):
        return None

    return data


def _build_index(planning_dir: Path) -> list[dict[str, str]]:
    """Scan *planning_dir* for ``.md`` files and return parsed doc entries."""
    docs: list[dict[str, str]] = []
    md_files = sorted(planning_dir.glob("*.md"))

    for md_path in md_files:
        fm = _parse_frontmatter(md_path)
        if fm is None:
            warnings.warn(
                f"No valid YAML frontmatter in {md_path.relative_to(PROJECT_ROOT)} — skipping",
                stacklevel=2,
            )
            continue

        title = fm.get("title", "")
        status = fm.get("status", "")
        created = fm.get("created", "")

        if not title or not status:
            warnings.warn(
                f"Missing title or status in frontmatter of "
                f"{md_path.relative_to(PROJECT_ROOT)} — skipping",
                stacklevel=2,
            )
            continue

        # Normalise created to string (could be a date object from yaml)
        if isinstance(created, datetime):
            created = created.strftime("%Y-%m-%d")
        elif created is None:
            created = ""
        else:
            created = str(created)

        docs.append(
            {
                "path": str(md_path.relative_to(PROJECT_ROOT)),
                "title": str(title),
                "status": str(status),
                "created": created,
            }
        )

    return docs


def _sort_docs(docs: list[dict[str, str]]) -> list[dict[str, str]]:
    """Sort by status group order then alphabetically by title."""
    return sorted(
        docs,
        key=lambda d: (
            STATUS_ORDER.get(d["status"], 999),
            d["title"].lower(),
        ),
    )


def _count_by_status(docs: list[dict[str, str]]) -> dict[str, int]:
    """Return counts keyed by status, ordered by STATUS_ORDER."""
    counts: dict[str, int] = {}
    for doc in docs:
        s = doc["status"]
        counts[s] = counts.get(s, 0) + 1

    # Sort by STATUS_ORDER (unknown statuses last, alphabetically)
    return dict(
        sorted(
            counts.items(),
            key=lambda kv: (STATUS_ORDER.get(kv[0], 999), kv[0]),
        )
    )


def main() -> None:
    """Scan planning docs and write STATUS.yaml."""
    parser = argparse.ArgumentParser(
        description="Index planning docs by YAML frontmatter"
    )
    parser.add_argument(
        "--planning-dir",
        type=Path,
        default=PROJECT_ROOT / "docs" / "planning",
        help="Directory containing planning Markdown files",
    )
    args = parser.parse_args()

    planning_dir: Path = args.planning_dir
    if not planning_dir.is_dir():
        print(f"ERROR: {planning_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    docs = _build_index(planning_dir)
    docs = _sort_docs(docs)
    by_status = _count_by_status(docs)

    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    output: dict[str, object] = {
        "generated": now,
        "total": len(docs),
        "by_status": by_status,
        "docs": docs,
    }

    output_path = planning_dir / "STATUS.yaml"

    header = (
        "# Auto-generated by scripts/index_planning_docs.py\n"
        "# Do not edit manually — regenerate with: "
        "uv run python scripts/index_planning_docs.py\n"
    )

    yaml_body = yaml.dump(
        output,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=120,
    )

    output_path.write_text(header + yaml_body, encoding="utf-8")

    # Print summary to stdout
    print(
        f"Indexed {len(docs)} planning docs → {output_path.relative_to(PROJECT_ROOT)}"
    )
    print()
    for status, count in by_status.items():
        print(f"  {status}: {count}")
    print()
    print(f"Generated: {now}")


if __name__ == "__main__":
    main()
