#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────
# DO NOT EDIT THIS FILE MANUALLY.
# It is generated by: bash scripts/oracle-bootstrap-local-key.sh
# That script generates an API key pair on your local machine and writes
# this file with YOUR public key and user OCID baked in.
#
# Then you paste this file's contents into OCI Cloud Shell — one time only.
# After that, your local machine can talk to Oracle forever.
# ──────────────────────────────────────────────────────────────────────────
echo "This file has not been generated yet."
echo "Run: bash scripts/oracle-bootstrap-local-key.sh"
echo "Then paste the generated file into OCI Cloud Shell."
