#!/usr/bin/env bash
# oracle-bootstrap-local-key.sh — Generate OCI API key and Cloud Shell upload script
#
# This is the FIRST thing you run for Oracle Cloud setup. It:
#   1. Reads OCI_USER_OCID from .env (you must set this first)
#   2. Generates an RSA key pair in ~/.oci/
#   3. Creates ~/.oci/config for the OCI CLI
#   4. Generates scripts/oci-cloud-shell-paste-this.sh with YOUR key baked in
#
# After running this, paste oci-cloud-shell-paste-this.sh into OCI Cloud Shell.
# That's the ONE manual browser step. Everything after is local CLI.
#
# Usage: bash scripts/oracle-bootstrap-local-key.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OCI_DIR="$HOME/.oci"
KEY_NAME="oci_api_key"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ─── Step 0: Read .env ─────────────────────────────────────────────────────

ENV_FILE="$REPO_ROOT/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    err ".env not found. Run: cp .env.example .env"
    exit 1
fi

# Source OCI variables from .env
OCI_USER_OCID=""
OCI_TENANCY_OCID=""
OCI_REGION=""
while IFS='=' read -r key value; do
    [[ -z "$key" || "$key" =~ ^# ]] && continue
    value="${value%\"}"
    value="${value#\"}"
    case "$key" in
        OCI_USER_OCID)    OCI_USER_OCID="$value" ;;
        OCI_TENANCY_OCID) OCI_TENANCY_OCID="$value" ;;
        OCI_REGION)       OCI_REGION="$value" ;;
    esac
done < <(grep -v '^\s*#' "$ENV_FILE" | grep -v '^\s*$')

if [[ -z "$OCI_USER_OCID" ]]; then
    err "OCI_USER_OCID is not set in .env"
    err ""
    err "To find it: OCI Console → avatar (top-right) → User settings → copy OCID"
    err "Then add to .env:  OCI_USER_OCID=ocid1.user.oc1..aaaa..."
    exit 1
fi

if [[ -z "$OCI_TENANCY_OCID" ]]; then
    err "OCI_TENANCY_OCID is not set in .env"
    exit 1
fi

if [[ -z "$OCI_REGION" ]]; then
    err "OCI_REGION is not set in .env"
    exit 1
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Oracle Cloud — Local API Key Bootstrap"
echo "═══════════════════════════════════════════════════════════════"
echo ""
info "User OCID:   $OCI_USER_OCID"
info "Tenancy:     $OCI_TENANCY_OCID"
info "Region:      $OCI_REGION"
echo ""

# ─── Step 1: Generate key pair ─────────────────────────────────────────────

mkdir -p "$OCI_DIR"

if [[ -f "$OCI_DIR/$KEY_NAME.pem" ]]; then
    warn "Key already exists: $OCI_DIR/$KEY_NAME.pem"
    echo -e "${YELLOW}>>> Overwrite? [y/N]${NC}"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        info "Keeping existing key."
    else
        rm -f "$OCI_DIR/$KEY_NAME.pem" "$OCI_DIR/${KEY_NAME}_public.pem"
    fi
fi

if [[ ! -f "$OCI_DIR/$KEY_NAME.pem" ]]; then
    info "Generating 2048-bit RSA key pair..."
    openssl genrsa -out "$OCI_DIR/$KEY_NAME.pem" 2048 2>/dev/null
    chmod 600 "$OCI_DIR/$KEY_NAME.pem"
    openssl rsa -pubout -in "$OCI_DIR/$KEY_NAME.pem" -out "$OCI_DIR/${KEY_NAME}_public.pem" 2>/dev/null
    ok "Key pair generated"
fi

# Compute fingerprint (OCI style: MD5 of DER-encoded public key)
FINGERPRINT=$(openssl rsa -pubout -outform DER -in "$OCI_DIR/$KEY_NAME.pem" 2>/dev/null | openssl md5 -c | awk '{print $2}')
ok "Fingerprint: $FINGERPRINT"

# ─── Step 2: Create ~/.oci/config ──────────────────────────────────────────

info "Writing $OCI_DIR/config ..."
cat > "$OCI_DIR/config" <<EOF
[DEFAULT]
user=$OCI_USER_OCID
fingerprint=$FINGERPRINT
tenancy=$OCI_TENANCY_OCID
region=$OCI_REGION
key_file=$OCI_DIR/$KEY_NAME.pem
EOF
chmod 600 "$OCI_DIR/config"
ok "OCI config written"

# ─── Step 3: Update .env with fingerprint ──────────────────────────────────

# Update OCI_FINGERPRINT in .env
if grep -q "^OCI_FINGERPRINT=" "$ENV_FILE"; then
    # Replace existing
    python3 -c "
import pathlib
p = pathlib.Path('$ENV_FILE')
content = p.read_text()
lines = content.split('\n')
for i, line in enumerate(lines):
    if line.startswith('OCI_FINGERPRINT='):
        lines[i] = 'OCI_FINGERPRINT=$FINGERPRINT'
p.write_text('\n'.join(lines))
"
    ok "Updated OCI_FINGERPRINT in .env"
else
    echo "OCI_FINGERPRINT=$FINGERPRINT" >> "$ENV_FILE"
    ok "Added OCI_FINGERPRINT to .env"
fi

# ─── Step 4: Generate Cloud Shell paste script ─────────────────────────────

PUBLIC_KEY=$(cat "$OCI_DIR/${KEY_NAME}_public.pem")
PASTE_SCRIPT="$REPO_ROOT/scripts/oci-cloud-shell-paste-this.sh"

cat > "$PASTE_SCRIPT" <<SCRIPT_EOF
#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED by oracle-bootstrap-local-key.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Paste this ENTIRE file into OCI Cloud Shell. ONE TIME ONLY.
# After this, your local machine can talk to Oracle forever.
# ──────────────────────────────────────────────────────────────────────────

cat > /tmp/pubkey.pem <<'EOF'
${PUBLIC_KEY}
EOF

oci iam user api-key upload \\
  --user-id $OCI_USER_OCID \\
  --key-file /tmp/pubkey.pem

rm -f /tmp/pubkey.pem
echo ""
echo "Done! If you see a fingerprint above, your local machine is authorized."
echo "Expected fingerprint: $FINGERPRINT"
echo "You can close Cloud Shell — it is never needed again."
SCRIPT_EOF

chmod +x "$PASTE_SCRIPT"
ok "Generated: scripts/oci-cloud-shell-paste-this.sh"

# ─── Summary ───────────────────────────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Next step: ONE manual browser action"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  1. Open OCI Cloud Shell in your browser:"
echo "     https://cloud.oracle.com → click the terminal icon (top-right)"
echo ""
echo "  2. Open scripts/oci-cloud-shell-paste-this.sh in a text editor"
echo "     Select all → Copy → Paste into Cloud Shell → press Enter"
echo ""
echo "  3. Verify it worked (run this on your LOCAL machine):"
echo "     oci iam region list"
echo ""
echo "  After that, run: bash scripts/oracle-setup-script.sh"
echo ""
