"""Generate ~/.sky/config.yaml from repo cloud config.

Ensures SkyPilot controller placement matches job cloud.
Called by run_factorial.sh before any sky jobs launch.

Cross-cloud SSH (e.g., RunPod controller for GCP jobs) adds ~30 min/submission
and creates single point of failure. 5th pass root cause.

Usage:
    uv run python scripts/sync_sky_config.py configs/cloud/gcp_spot.yaml
    uv run python scripts/sync_sky_config.py configs/cloud/runpod_dev.yaml
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml


def sync_sky_config(cloud_config_path: Path) -> None:
    """Write ~/.sky/config.yaml controller block from repo cloud config.

    Preserves existing non-controller settings in ~/.sky/config.yaml.
    Only overwrites the jobs.controller.resources block.
    """
    cloud_cfg = yaml.safe_load(cloud_config_path.read_text(encoding="utf-8"))
    controller = cloud_cfg.get("controller")

    if controller is None:
        # Local execution — no SkyPilot config needed
        print("No controller block in config — skipping ~/.sky/config.yaml sync")
        return

    controller_cloud = controller["cloud"]
    disk_size = controller.get("disk_size", 50)

    sky_config_path = Path.home() / ".sky" / "config.yaml"
    sky_config_path.parent.mkdir(parents=True, exist_ok=True)

    # Read existing config to preserve non-controller settings
    existing: dict = {}
    if sky_config_path.exists():
        existing = yaml.safe_load(sky_config_path.read_text(encoding="utf-8")) or {}

    # Update only the controller block
    existing.setdefault("jobs", {})["controller"] = {
        "resources": {
            "cloud": controller_cloud,
            "disk_size": disk_size,
        },
    }

    sky_config_path.write_text(
        f"# AUTO-GENERATED by scripts/sync_sky_config.py\n"
        f"# Source: {cloud_config_path}\n"
        f"# Controller MUST match job cloud. Do not edit manually.\n"
        + yaml.dump(existing, default_flow_style=False),
        encoding="utf-8",
    )
    print(f"Synced ~/.sky/config.yaml (controller: {controller_cloud})")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <cloud-config.yaml>")
        sys.exit(1)
    sync_sky_config(Path(sys.argv[1]))
