# Based on the "env_docker-image.yml" (that builds "petteriteikari/minivess-mlops-env:latest")
name: Docker (App)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dockerhub login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run:
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - name: Upgrade Docker Compose to 2.x
      run: sudo apt update && sudo apt install docker-compose-plugin
    - name: Check Docker Compose version
      run: docker-compose --version
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yml build --progress=plain --no-cache
        # AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} \
      #        AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} \
    - name: Push the image to Dockerhub
      run: docker push petteriteikari/minivess-mlops-train:latest
