# Based on the "env_docker-image.yml" (that builds "petteriteikari/minivess-mlops-env:latest")
name: Docker (App)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Upgrade Docker Compose to 2.x # https://github.com/marketplace/actions/docker-compose-setup
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        version: v2.3.3 # defaults to 'latest'
        legacy: true # will also install in PATH as `docker-compose`
    - name: Check Docker Compose version
      run: docker-compose --version
    - name: Build the Docker image
      run: AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} \
        AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} \
        docker compose -f docker-compose.yml build --progress=plain # --no-cache
    # See e.g. https://github.com/docker/build-push-action/tree/v3#inputs
    - name: Push the image to Dockerhub
      run: docker push petteriteikari/minivess-mlops-train:latest
