name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dockerhub login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run:
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag petteriteikari/minivess-mlops:${{ github.sha }}
    - name: Push the image to Dockerhub
      run: docker push petteriteikari/minivess-mlops:${{ github.sha }}
