name: Docker Image CI

on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
  push:
    paths:
      # Only need to build the image when Poetry environment or the Dockerfile itself has changed
      # atm as no code is executed there, but the Docker is only used as a Pycharm Interpreter
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dockerhub login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run:
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag petteriteikari/minivess-mlops:${{ github.sha }}
    - name: Push the image to Dockerhub
      run: docker push petteriteikari/minivess-mlops:${{ github.sha }}
