name: Test dataload CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - name: dockerhub login
        env:
          DOCKERHUB_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
          MLFLOW_USER: ${{secrets.MLFLOW_USERNAME}}
          MLFLOW_PASSWORD: ${{secrets.MLFLOW_PASSWORD}}
        run:
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      # RUN THE CODE WITH THE DOCKER IMAGE: petteriteikari/minivess-mlops-env:latest
      - name: execute py script in Docker
        run: docker run --rm petteriteikari/minivess-mlops:latest \ # Docker Image
          && python run_training.py  \ # Python script
          && -c task_config.yaml -run test_dataload # Input arguments

