name: Test (Dataload)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
      - name: dockerhub login
        env:
          DOCKERHUB_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run:
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - name: pull Docker image
        run: docker pull petteriteikari/minivess-mlops-train:latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-north-1
      - name: Create AWS credentials on-the-fly
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{secrets.AWS_ACCESS_KEY_ID}}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{secrets.AWS_SECRET_ACCESS_KEY}}" >> ~/.aws/credentials
      - name: Check diskspace before DVC pull
        run: sudo df -h
      - name: Install DVC
        uses: iterative/setup-dvc@v1
      - name: Create directory for DVC cache
        run: mkdir -p /mnt/minivess-dvc-cache
      - name: Pull data from DVC
        run:
          #dvc remote modify remote_storage access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          #dvc remote modify remote_storage secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dvc pull
      - name: Check diskspace after DVC pull
        run: sudo df -h
      - name: Create directory for artifacts
        run: mkdir -p /mnt/minivess-artifacts
      - name: Testing data loading (training_run)
        env:
          MLFLOW_USER: ${{secrets.MLFLOW_USERNAME}}
          MLFLOW_PASSWORD: ${{secrets.MLFLOW_PASSWORD}}
        run: >
          docker run -it \ 
          -v ${HOME}/.aws:/home/minivessuser/.aws:ro \ 
          -e S3_ARTIFACTS=minivess-artifacts \    
          -e DOCKER_ARTIFACTS=/mnt/minivess-artifacts \
          -e S3_CACHE=minivess-dvc-cache \   
          -e DOCKER_CACHE=/mnt/minivess-dvc-cache \    
          --privileged --cap-add SYS_ADMIN --device /dev/fuse \ 
          petteriteikari/minivess-mlops-train \
          -c task_config.yaml -run test_dataload

