"""Job manifest data model for factorial experiment monitoring.

The manifest is the single source of truth consumed by monitor_factorial.py.
It contains per-job metadata (expected durations, hourly rates, spot/on-demand)
and experiment-level config (budget caps, kill-switch thresholds).

Generated by: scripts/create_job_manifest.py (or run_factorial.sh integration)
Consumed by:  scripts/monitor_factorial.py

See: docs/planning/v0-2_archive/original_docs/experiment-harness-improvement-plan.xml
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path  # noqa: TC003

logger = logging.getLogger(__name__)

# Terminal statuses — job is done (succeeded or failed).
TERMINAL_STATUSES = frozenset({
    "SUCCEEDED",
    "FAILED",
    "FAILED_SETUP",
    "CANCELLED",
})

# Active statuses — job is still running or waiting.
ACTIVE_STATUSES = frozenset({
    "PENDING",
    "STARTING",
    "RUNNING",
    "RECOVERING",
})


@dataclass
class JobRecord:
    """Per-job metadata and runtime state.

    Attributes
    ----------
    job_id:
        SkyPilot managed job ID (None before submission).
    condition_name:
        Factorial condition identifier (e.g., "dynunet-dice_ce-calibfalse-f0").
    model:
        Model family name.
    loss:
        Loss function name.
    fold:
        Cross-validation fold index.
    spot:
        Whether the job uses spot/preemptible instances.
    expected_duration_minutes:
        Expected total job duration (setup + training + upload).
    warn_duration_minutes:
        Duration threshold for WARNING alert (typically 3x expected).
    cancel_duration_minutes:
        Duration threshold for auto-CANCEL (hard limit).
    hourly_rate:
        GPU cost in USD/hour for this job's GPU type + spot/on-demand.
    status:
        Current SkyPilot job status.
    launched_at:
        ISO 8601 UTC timestamp when the job was submitted.
    started_at:
        ISO 8601 UTC timestamp when the job first reached RUNNING.
    ended_at:
        ISO 8601 UTC timestamp when the job reached a terminal status.
    failure_category:
        Diagnosis category from ralph_monitor (e.g., "OOM", "SPOT_PREEMPTION").
    recovery_count:
        Number of spot preemption recoveries.
    """

    job_id: int | None
    condition_name: str
    model: str
    loss: str
    fold: int
    spot: bool
    expected_duration_minutes: float
    warn_duration_minutes: float
    cancel_duration_minutes: float
    hourly_rate: float
    status: str
    launched_at: str | None = None
    started_at: str | None = None
    ended_at: str | None = None
    failure_category: str | None = None
    recovery_count: int = 0

    @classmethod
    def from_dict(cls, d: dict) -> JobRecord:
        """Construct a JobRecord from a dictionary."""
        return cls(
            job_id=d.get("job_id"),
            condition_name=d["condition_name"],
            model=d["model"],
            loss=d["loss"],
            fold=d["fold"],
            spot=d["spot"],
            expected_duration_minutes=float(d["expected_duration_minutes"]),
            warn_duration_minutes=float(d["warn_duration_minutes"]),
            cancel_duration_minutes=float(d["cancel_duration_minutes"]),
            hourly_rate=float(d["hourly_rate"]),
            status=d.get("status", "PENDING"),
            launched_at=d.get("launched_at"),
            started_at=d.get("started_at"),
            ended_at=d.get("ended_at"),
            failure_category=d.get("failure_category"),
            recovery_count=d.get("recovery_count", 0),
        )

    def to_dict(self) -> dict:
        """Serialize to a JSON-compatible dictionary."""
        return asdict(self)

    @property
    def elapsed_minutes(self) -> float:
        """Minutes since launched_at (or 0 if not launched)."""
        if self.launched_at is None:
            return 0.0

        launched = datetime.fromisoformat(self.launched_at)
        if self.ended_at is not None:
            end = datetime.fromisoformat(self.ended_at)
        else:
            end = datetime.now(UTC)
        delta = end - launched
        return delta.total_seconds() / 60.0

    @property
    def cost_usd(self) -> float:
        """Accumulated cost in USD (elapsed_hours * hourly_rate)."""
        return (self.elapsed_minutes / 60.0) * self.hourly_rate

    @property
    def is_terminal(self) -> bool:
        """Whether the job has reached a terminal status."""
        return self.status in TERMINAL_STATUSES

    @property
    def is_active(self) -> bool:
        """Whether the job is still active (not terminal)."""
        return self.status in ACTIVE_STATUSES


@dataclass
class JobManifest:
    """Experiment-level container for all job records.

    The manifest is the single configuration file consumed by the monitor.
    It contains everything the monitor needs: job metadata, budget caps,
    kill-switch thresholds, and expected durations.

    Attributes
    ----------
    experiment_name:
        Name of the factorial experiment.
    config_file:
        Path to the factorial YAML config.
    budget_warning_usd:
        Budget threshold for WARNING alert.
    budget_cap_usd:
        Budget threshold for STOP (cancel all jobs).
    pending_timeout_minutes:
        How long a job can stay PENDING before alerting.
    kill_switch_threshold:
        Number of identical failures before kill-switch triggers.
    kill_switch_window_minutes:
        Time window for counting kill-switch failures.
    batch_failure_pct:
        Fraction of batch that must fail to trigger kill-switch.
    launched_at:
        ISO 8601 UTC timestamp when the experiment was launched.
    jobs:
        List of all job records.
    """

    experiment_name: str
    config_file: str
    budget_warning_usd: float
    budget_cap_usd: float
    pending_timeout_minutes: float
    kill_switch_threshold: int
    kill_switch_window_minutes: float
    batch_failure_pct: float
    launched_at: str
    jobs: list[JobRecord] = field(default_factory=list)

    @classmethod
    def from_json(cls, path: Path) -> JobManifest:
        """Load a manifest from a JSON file.

        Raises
        ------
        ValueError
            If required fields are missing.
        FileNotFoundError
            If the file does not exist.
        """
        data = json.loads(path.read_text(encoding="utf-8"))

        required = {
            "experiment_name",
            "config_file",
            "budget_warning_usd",
            "budget_cap_usd",
            "pending_timeout_minutes",
            "kill_switch_threshold",
            "kill_switch_window_minutes",
            "batch_failure_pct",
            "launched_at",
            "jobs",
        }
        missing = required - set(data.keys())
        if missing:
            msg = f"Manifest missing required fields: {sorted(missing)}"
            raise ValueError(msg)

        jobs = [JobRecord.from_dict(j) for j in data["jobs"]]

        return cls(
            experiment_name=data["experiment_name"],
            config_file=data["config_file"],
            budget_warning_usd=float(data["budget_warning_usd"]),
            budget_cap_usd=float(data["budget_cap_usd"]),
            pending_timeout_minutes=float(data["pending_timeout_minutes"]),
            kill_switch_threshold=int(data["kill_switch_threshold"]),
            kill_switch_window_minutes=float(data["kill_switch_window_minutes"]),
            batch_failure_pct=float(data["batch_failure_pct"]),
            launched_at=data["launched_at"],
            jobs=jobs,
        )

    def to_json(self, path: Path) -> None:
        """Write manifest to JSON file (atomic: write to .tmp then rename)."""
        data = {
            "experiment_name": self.experiment_name,
            "config_file": self.config_file,
            "budget_warning_usd": self.budget_warning_usd,
            "budget_cap_usd": self.budget_cap_usd,
            "pending_timeout_minutes": self.pending_timeout_minutes,
            "kill_switch_threshold": self.kill_switch_threshold,
            "kill_switch_window_minutes": self.kill_switch_window_minutes,
            "batch_failure_pct": self.batch_failure_pct,
            "launched_at": self.launched_at,
            "jobs": [j.to_dict() for j in self.jobs],
        }
        tmp_path = path.with_suffix(".tmp")
        tmp_path.write_text(
            json.dumps(data, indent=2, default=str),
            encoding="utf-8",
        )
        tmp_path.rename(path)

    @property
    def job_count(self) -> int:
        """Total number of jobs in the manifest."""
        return len(self.jobs)

    @property
    def active_jobs(self) -> list[JobRecord]:
        """Jobs that are still active (not terminal)."""
        return [j for j in self.jobs if j.is_active]

    @property
    def terminal_jobs(self) -> list[JobRecord]:
        """Jobs that have reached a terminal status."""
        return [j for j in self.jobs if j.is_terminal]

    @property
    def total_cost(self) -> float:
        """Total accumulated cost across all jobs."""
        return sum(j.cost_usd for j in self.jobs)

    @property
    def success_rate(self) -> float:
        """Fraction of terminal jobs that SUCCEEDED (0.0 if none terminal)."""
        terminal = self.terminal_jobs
        if not terminal:
            return 0.0
        succeeded = sum(1 for j in terminal if j.status == "SUCCEEDED")
        return succeeded / len(terminal)

    @property
    def all_terminal(self) -> bool:
        """Whether all jobs have reached a terminal status."""
        return all(j.is_terminal for j in self.jobs)
